import { createRouter, createWebHashHistory, RouteRecordRaw } from 'vue-router'

export const routes: RouteRecordRaw[] = [
  {
    path: '/',
    name: 'Layout',
    component: () => import('@/views/home/index.vue'),
    redirect: '/home',
    children: [
      {
        path: '/home',
        name: 'Home',
        component: () => import('@/views/home/index.vue'),
        meta: {
          title: '首页',
          keepAlive: true,
          icon: 'House',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
    ],
    meta: {
      title: '',
      keepAlive: true,
      icon: '',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/screen',
    name: 'Screen',
    component: () => import('@/views/screen/index.vue'),
    meta: {
      title: '数据大屏',
      keepAlive: true,
      icon: 'PieChart',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/login',
    },
  },
  {
    path: '/bookmark',
    name: 'Bookmark',
    component: () => import('@/views/bookmark/index.vue'),
    meta: {
      title: '书签管理',
      keepAlive: true,
      icon: 'Memo',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/login',
    },
  },
  {
    path: '/spider',
    name: 'Spider',
    component: () => import('@/views/bookmark/index.vue'),
    meta: {
      title: '爬虫管理',
      keepAlive: true,
      icon: 'Box',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/login',
    },
  },
  {
    path: '/jobs',
    name: 'Jobs',
    component: () => import('@/views/bookmark/index.vue'),
    meta: {
      title: '任务管理',
      keepAlive: true,
      icon: 'Timer',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/login',
    },
  },
  {
    path: '/ChatGpt',
    name: 'ChatGpt',
    // component: () => import('@/layout/index.vue'),
    children: [
      {
        path: '/ApiConfig',
        name: 'ApiConfig',
        component: () => import('@/views/chatGpt/ApiConfig/index.vue'),
        meta: {
          title: 'Api配置',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/chatModel',
        name: 'chatModel',
        component: () => import('@/views/chatGpt/ChatModel/index.vue'),
        meta: {
          title: '对话角色模型',
          keepAlive: true,
          icon: 'Avatar',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/menus',
        },
      },
      {
        path: '/chatPanel',
        name: 'chatPanel',
        component: () => import('@/views/chatGpt/ChatPanel/index.vue'),
        meta: {
          title: '对话页面',
          keepAlive: true,
          icon: 'Lock',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
    ],
    meta: {
      title: 'ChatGpt整合',
      keepAlive: true,
      icon: 'Menu',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/accountMange',
    name: 'accountMange',
    // component: () => import('@/layout/index.vue'),
    children: [
      {
        path: '/platforms',
        name: 'platforms',
        component: () => import('@/views/AccountMange/Platforms/index.vue'),
        meta: {
          title: '接码平台管理',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/accountMaking',
        name: 'accountMaking',
        component: () => import('@/views/AccountMange/AccountMaking/index.vue'),
        meta: {
          title: '虚拟账号生成',
          keepAlive: true,
          icon: 'Avatar',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/menus',
        },
      },
      {
        path: '/authMange',
        name: 'authMange',
        component: () => import('@/views/AccountMange/AuthMange/index.vue'),
        meta: {
          title: '账号权限管理',
          keepAlive: true,
          icon: 'Lock',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
    ],
    meta: {
      title: '虚拟账号管理',
      keepAlive: true,
      icon: 'Menu',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/counponClip',
    name: 'counponClip',
    // component: () => import('@/layout/index.vue'),
    children: [
      {
        path: '/cataory',
        name: 'cataory',
        component: () => import('@/views/CounponClip/Catacorys/index.vue'),
        meta: {
          title: '优惠种类',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/pushRules',
        name: 'pushRules',
        component: () => import('@/views/CounponClip/PushRules/index.vue'),
        meta: {
          title: '推送规则',
          keepAlive: true,
          icon: 'Avatar',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/menus',
        },
      },
    ],
    meta: {
      title: '薅羊毛',
      keepAlive: true,
      icon: 'Menu',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/Emarketing',
    name: 'Emarketing',
    // component: () => import('@/layout/index.vue'),
    children: [
      {
        path: '/feeConfig',
        name: 'feeConfig',
        component: () => import('@/views/EMarketing/FeeConfig/index.vue'),
        meta: {
          title: '费用配置',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/platforms',
        name: 'platforms',
        component: () => import('@/views/EMarketing/PlatForms/index.vue'),
        meta: {
          title: '电商平台',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
    ],
    meta: {
      title: '电商营销管理',
      keepAlive: true,
      icon: 'Menu',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/news',
    name: 'news',
    // component: () => import('@/layout/index.vue'),
    children: [
      {
        path: '/cataorys',
        name: 'cataorys',
        component: () => import('@/views/news/Cataorys/index.vue'),
        meta: {
          title: '新闻类别',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/pushRules',
        name: 'pushRules',
        component: () => import('@/views/news/PushStyle/index.vue'),
        meta: {
          title: '推送规则',
          keepAlive: true,
          icon: 'Avatar',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/menus',
        },
      },
      {
        path: '/spiderConfig',
        name: 'spiderConfig',
        component: () => import('@/views/news/SpiderConfig/index.vue'),
        meta: {
          title: '爬虫配置',
          keepAlive: true,
          icon: 'Lock',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/spiders',
        name: 'spiders',
        component: () => import('@/views/news/Spiders/index.vue'),
        meta: {
          title: '爬虫管理',
          keepAlive: true,
          icon: 'Monitor',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
    ],
    meta: {
      title: '新闻推送',
      keepAlive: true,
      icon: 'Menu',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/Nmedia',
    name: 'Nmedia',
    // component: () => import('@/layout/index.vue'),
    children: [
      {
        path: '/copyWritingConfig',
        name: 'copyWritingConfig',
        component: () => import('@/views/Nmedia/CopywritingConfig/index.vue'),
        meta: {
          title: '视频文案配置',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/platforms',
        name: 'platforms',
        component: () => import('@/views/Nmedia/Platforms/index.vue'),
        meta: {
          title: '短视频平台',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/videoCreate',
        name: 'videoCreate',
        component: () => import('@/views/Nmedia/VidoeCreate/index.vue'),
        meta: {
          title: '视频创作',
          keepAlive: true,
          icon: 'Lock',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/3rdVideos',
        name: '3rdVideos',
        component: () => import('@/views/Nmedia/3rdVideos/index.vue'),
        meta: {
          title: '第三方视频',
          keepAlive: true,
          icon: 'Monitor',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
    ],
    meta: {
      title: '新媒体运营',
      keepAlive: true,
      icon: 'Menu',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/menuMange',
    name: 'MenuMange',
    // component: () => import('@/layout/index.vue'),
    children: [
      {
        path: '/userMange',
        name: 'UserMange',
        component: () => import('@/views/menus/user/index.vue'),
        meta: {
          title: '用户管理',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/roleMange',
        name: 'RoleMange',
        component: () => import('@/views/menus/role/index.vue'),
        meta: {
          title: '角色管理',
          keepAlive: true,
          icon: 'Avatar',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/menus',
        },
      },
      {
        path: '/privilegeMange',
        name: 'PrivilegeMange',
        component: () => import('@/views/menus/privi/index.vue'),
        meta: {
          title: '权限管理',
          keepAlive: true,
          icon: 'Lock',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/systemLog',
        name: 'SystemLog',
        component: () => import('@/views/menus/syslog/index.vue'),
        meta: {
          title: '系统日志',
          keepAlive: true,
          icon: 'Monitor',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/configMange',
        name: 'ConfigMange',
        component: () => import('@/views/menus/config/index.vue'),
        meta: {
          title: '配置管理',
          keepAlive: true,
          icon: 'Setting',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
    ],
    meta: {
      title: '菜单管理',
      keepAlive: true,
      icon: 'Menu',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/projects',
    name: 'projects',
    // component: () => import('@/layout/index.vue'),
    children: [
      {
        path: '/codeGen',
        name: 'codeGen',
        component: () => import('@/views/Projects/CodeGen/index.vue'),
        meta: {
          title: '代码生成',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/groupMange',
        name: 'groupMange',
        component: () => import('@/views/Projects/GroupMange/index.vue'),
        meta: {
          title: '团队管理',
          keepAlive: true,
          icon: 'Avatar',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/menus',
        },
      },
    ],
    meta: {
      title: '项目管理',
      keepAlive: true,
      icon: 'Menu',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/devops',
    name: 'devops',
    // component: () => import('@/layout/index.vue'),
    children: [
      {
        path: '/alter',
        name: 'alter',
        component: () => import('@/views/Devops/alter/index.vue'),
        meta: {
          title: '告警触发',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/monitr',
        name: 'monitr',
        component: () => import('@/views/Devops/monitr/index.vue'),
        meta: {
          title: '监控展示',
          keepAlive: true,
          icon: 'Avatar',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/menus',
        },
      },
      {
        path: '/cloudPlatform',
        name: 'cloudPlatform',
        component: () => import('@/views/Devops/CloudPlatform/index.vue'),
        meta: {
          title: '云厂商服务整合',
          keepAlive: true,
          icon: 'Lock',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/containers',
        name: 'containers',
        component: () => import('@/views/Devops/containers/index.vue'),
        meta: {
          title: '容器镜像管理',
          keepAlive: true,
          icon: 'Monitor',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/scripts',
        name: 'scripts',
        component: () => import('@/views/Devops/containers/index.vue'),
        meta: {
          title: '运维脚本管理',
          keepAlive: true,
          icon: 'Setting',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
    ],
    meta: {
      title: '运维中心',
      keepAlive: true,
      icon: 'Menu',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/unity',
    name: 'Unity',
    // component: () => import('@/layout/index.vue'),
    children: [
      {
        path: '/AiGen',
        name: 'AiGen',
        component: () => import('@/views/Unity/AiGen/index.vue'),
        meta: {
          title: 'AI生成',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/assets',
        name: 'assets',
        component: () => import('@/views/Unity/Assets/index.vue'),
        meta: {
          title: '游戏资产管理',
          keepAlive: true,
          icon: 'Avatar',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/menus',
        },
      },
      {
        path: '/workflow',
        name: 'workflow',
        component: () => import('@/views/Unity/WorkFlow/index.vue'),
        meta: {
          title: '工作流整合',
          keepAlive: true,
          icon: 'Lock',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
    ],
    meta: {
      title: 'Unity游戏开发',
      keepAlive: true,
      icon: 'Menu',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/Sd',
    name: 'Sd',
    // component: () => import('@/layout/index.vue'),
    children: [
      {
        path: '/aiModels',
        name: 'aiModels',
        component: () => import('@/views/SD/AiModels/index.vue'),
        meta: {
          title: 'AI模型',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/psTuning',
        name: 'psTuning',
        component: () => import('@/views/SD/PsTuning/index.vue'),
        meta: {
          title: 'ps微调',
          keepAlive: true,
          icon: 'Avatar',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/menus',
        },
      },
      {
        path: '/renderFram',
        name: 'renderFram',
        component: () => import('@/views/SD/RenderFram/index.vue'),
        meta: {
          title: '渲染农场',
          keepAlive: true,
          icon: 'Lock',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/cataorys',
        name: 'cataorys',
        component: () => import('@/views/SD/cataorys/index.vue'),
        meta: {
          title: '应用场景类别',
          keepAlive: true,
          icon: 'Monitor',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
    ],
    meta: {
      title: 'AI绘画整合',
      keepAlive: true,
      icon: 'Menu',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/login/index.vue'),
    meta: {
      title: '登录',
      keepAlive: true,
      icon: 'el-icon-s-home',
      hidden: true,
      affix: true,
      breadcrumb: false,
      activeMenu: '/login',
    },
  },
  {
    path: '/about',
    name: 'About',
    component: () => import('@/views/about/index.vue'),
    meta: {
      title: '关于',
      keepAlive: true,
      icon: 'Reading',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/about',
    },
  },
  {
    path: '/404',
    name: '404',
    component: () => import('@/views/404/index.vue'),
    meta: {
      title: '404',
      keepAlive: true,
      icon: 'el-icon-s-home',
      hidden: true,
      affix: true,
      breadcrumb: false,
      activeMenu: '/404',
    },
  },
]

const router = createRouter({
  history: createWebHashHistory(),
  routes,
  scrollBehavior: () => ({ left: 0, top: 0 }),
})

export default router
